# 03 - numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

## Python List 的特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [6]:
L[5] = 'Machine Learning'
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [7]:
import array

In [8]:
# array.array()中的第一个参数表示我们存储的数据类型，在这里 i 表示的是整型
# array.array()中的第二个参数使用的是List的生成表达式的方式来进行生成的
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5]

5

In [10]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [11]:
# arr[5] = 'Machine Learning'
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array

In [12]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr.shape

(10,)

In [14]:
nparr[5]

5

In [15]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
# nparr[5] = 'Machine Learning'
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [17]:
# dtype其实就是datatype的缩写
nparr.dtype

dtype('int32')

In [18]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr[3] = 3.14

In [21]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr.dtype

dtype('int32')

In [23]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [24]:
nparr2.shape

(3,)

In [25]:
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

In [30]:
# zeros，顾名思义就是创建一个零数组或者是零矩阵
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10).dtype

dtype('float64')

In [32]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
 np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape = (3, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(10).dtype

dtype('float64')

In [39]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((3, 5)).dtype

dtype('float64')

In [42]:
np.full(shape = (3, 5) ,fill_value  = 666, dtype = float)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [49]:
np.full(shape = (3, 5), fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [50]:
np.full(shape = (3, 5), fill_value = 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [53]:
np.full(fill_value = 666.0, shape = (3, 5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [51]:
np.full(shape = (3, 5), fill_value = 666.0).dtype

dtype('float64')

In [52]:
np.full(shape = (3, 5), fill_value = 666).dtype

dtype('int32')