# 03 - numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

## Python List 的特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [6]:
L[5] = 'Machine Learning'
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [7]:
import array

In [8]:
# array.array()中的第一个参数表示我们存储的数据类型，在这里 i 表示的是整型
# array.array()中的第二个参数使用的是List的生成表达式的方式来进行生成的
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5]

5

In [10]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [11]:
# arr[5] = 'Machine Learning'
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array

In [12]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr.shape

(10,)

In [14]:
nparr[5]

5

In [15]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
# nparr[5] = 'Machine Learning'
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [17]:
# dtype其实就是datatype的缩写
nparr.dtype

dtype('int32')

In [18]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr[3] = 3.14

In [21]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr.dtype

dtype('int32')

In [23]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [24]:
nparr2.shape

(3,)

In [25]:
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

In [26]:
# zeros，顾名思义就是创建一个零数组或者是零矩阵
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10).dtype

dtype('float64')

In [28]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
 np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros(shape = (3, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones(10).dtype

dtype('float64')

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((3, 5)).dtype

dtype('float64')

In [35]:
np.full(shape = (3, 5) ,fill_value  = 666, dtype = float)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [36]:
np.full(shape = (3, 5), fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [37]:
np.full(shape = (3, 5), fill_value = 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [38]:
np.full(fill_value = 666.0, shape = (3, 5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [39]:
np.full(shape = (3, 5), fill_value = 666.0).dtype

dtype('float64')

In [40]:
np.full(shape = (3, 5), fill_value = 666).dtype

dtype('int32')

In [41]:
np.full(shape = 10 ,fill_value = 12)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

### arange

In [42]:
# range()中最多可以传入3个参数，第1个参数是起始点，第2个参数是终止点，注意这个终止点是不包含的点
# 第3个参数是步长，步长如果不填的话就是默认为 1 
# 结果显示了一个[0, 20)前闭后开的步长为 2 的列表
# 下面为Python中常用的生成表达式的示例，这种示例比for循环更加的高效
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
# np.arange()中的参数的意义和Python中range()的意义是一模一样的
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
# 在Python中的range函数中，不能传入一个浮点数
# [i for i in range(0, 1, 0.2)]

In [45]:
#  而在np.array中是可以传入一个浮点数的
np.arange(0, 1 , 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [46]:
# np.arange()中如果不填写默认值的话也是默认为 1，这个跟Python中的range()函数是一致的
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# np.arange()中如果不填写第 1 个参数的话，也是默认为 0，这个跟Python中的range()也是一致的
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [48]:
# 在 0 到 20 之间等长的截取出 10 个点，这 10 个点是包含 0 和 20 这两个点的
np.linspace(0, 20 ,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [49]:
# np.linspace()这个函数中终止点是包含进我们的数组的，与此同时，第 3 个参数不是代表的步长
# 第 3 个参数是表示在我们的前闭后闭的区间中一共需要截取多少个点
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [50]:
# np.random.randint()也是一个前闭后开的方式，下面这段代码表示的是从 0 到 9
np.random.randint(0, 10)

7

In [51]:
# 当我们传入第 3 个参数的时候代表着我们想要生成 1 个数组（向量），而不仅仅是一个数
np.random.randint(0, 10, 10)

array([6, 8, 2, 8, 1, 2, 0, 8, 6, 3])

In [52]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
# 生成一个一维的大小从 4 到 7 的随机矩阵，数组（矩阵）的大小为 10
np.random.randint(4, 8, size = 10)

array([6, 4, 7, 5, 5, 5, 4, 7, 7, 5])

In [60]:
# 生成一个二维的大小从 4 到 7 的随机矩阵，数组（矩阵）的大小为 3行 5列
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [61]:
# 在之后的机器学习的算法中，有时我们会用到随机的向量或者随机的矩阵，不过这就造成了一个麻烦，
# 因为我们每次取的都是一个随机的向量或者矩阵，使得我们每次运行计算得出来的结果可能是不一致的，
# 这就为我们调试算法带来了一些麻烦
# 在计算机中，所有的随机数都是伪随机数，都是靠随机数生成算法来完成的
# 推动这个算法来生成一个一个的随机数，都会有一个随机的种子
# 对于这个随机的种子，我们可以显示的指定它

In [62]:
np.random.randint(4, 8, size = (3, 5))

array([[4, 7, 4, 4, 4],
       [4, 4, 4, 6, 6],
       [6, 7, 4, 5, 4]])

In [63]:
np.random.seed(666)
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [64]:
np.random.seed(666)
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [65]:
# np.random.random()默认生成的就是[0, 1)之间的随机数
# 在这里生成的随机的浮点数为在[0, 1)之间均匀分布的浮点数
np.random.random()

0.2811684913927954

In [67]:
# np.random.random()中传入的参数默认为 size 的值
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [68]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [69]:
# 生成符合正态分布的浮点数，符合均值为 0 ，方差为 1 的浮点数
np.random.normal()

0.7760516793129695

In [73]:
# 指定均值和方差，下面指定了均值为 10，方差为 100
np.random.normal(10, 100)

-69.7835721331366

In [75]:
# 均值为 0 ，方差为 1，size为(3, 5)
np.random.normal(0 ,1, (3, 5))

array([[ 0.92487532,  0.18305429,  0.34543496, -0.8131543 ,  1.06325382],
       [ 0.25866385,  0.47285107,  1.0319698 , -0.16045655,  0.00592353],
       [-0.53452616,  1.15170083, -1.34498108, -0.36119241, -1.15146822]])

In [77]:
# 均值叫做loc，默认值为 0.0 ,方差叫做scale，默认值为 1.0 ,大小叫做size
np.random.normal?

In [78]:
np.random?

In [79]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap