In [1]:
import numpy as np

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [7]:
# .ndim 用来查看是几维数组
x.ndim

1

In [9]:
X.ndim

2

In [10]:
# shape返回的是一个元祖
x.shape

(10,)

In [11]:
X.shape

(3, 5)

In [12]:
# size用来表示元素的个数
x.size

10

In [13]:
X.size

15

### numpy.array 的数据访问

In [14]:
# 对于Python的数据访问方法，也同样可以用于进行numpy.array的数据访问
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [16]:
# 索引为 -1 表示的是访问最后一个元素
x[-1]

9

In [17]:
# 在numpy中是不建议这么写的 
X[0][0]

0

In [18]:
# 其实是可以不用加圆括号的
X[(0, 0)]

0

In [19]:
X[(2, 2)]

12

In [20]:
X[0, 0]

0

In [21]:
X[2, 2]

12

In [22]:
# 从 0 开始，但是不包含 5
x[0:5]

array([0, 1, 2, 3, 4])

In [23]:
# 冒号前面的参数不写的话，就是从头开始访问
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
# 冒号后面的数不写的话，就是一直访问到结尾
x[5:]

array([5, 6, 7, 8, 9])

In [25]:
# 对于切片来说，和我们的range()函数是一样的，它支持第 3个参数，也就是步长
# 表示从头访问到尾，并且步长为 2
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
# 负数代表着倒着访问
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
x[::-2]

array([9, 7, 5, 3, 1])

In [28]:
# 切片的语法本身也可以非常方便地应用于二维数组中
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
# 想访问 X 的前两行的前三列
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])