# NumPy 中的矩阵运算

给定一个向量，让向量中的每一个数都乘以2

a = (0, 1 ,2) 

a * 2 = (0, 2, 4)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
# 在 Python 语言中，对于 List 本身是不支持直接使用 2 * L 这样的操作的
# 2 * L 其实是将 2 个 L 首尾衔接了起来
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(2 * e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A = []
for e in L:
    A.append(2 * e)
A

Wall time: 144 ms


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [6]:
%%time
# 使用 for 循环的效率是要远远的慢于生成表达式的
A = [2 * i for i in L]

Wall time: 111 ms


In [7]:
import numpy as np
L = np.arange(n)

In [8]:
%%time
# 使用 NumPy.array 来实现这种运算是大大的快于使用原生的 List
A = np.array(2 * e for e in L)
A

Wall time: 14 ms


array(<generator object <genexpr> at 0x00000200954E2408>, dtype=object)

In [9]:
%%time
# 在 numpy.array中它将每一个数组看作是向量或者是矩阵
A = 2 * L
A

Wall time: 1.96 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [10]:
%%time
# 在numpy中，它本身将数组当成是向量，将二维数组看作是矩阵，直接就支持很多向量和矩阵相关的运算
# 这里有一点需要注意的问题是 %%time 必须要写在代码的第一行，否则会报错
n = 10
L = np.arange(n)
2 * L

Wall time: 0 ns


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Functions

In [11]:
# 将数组看作是向量或者是矩阵进行的运算有一个特殊的名字叫做 Universal Functions
X = np.arange(1, 16).reshape(3, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
# 将 X 矩阵中所有的元素都加了 1
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
# 将 X 矩阵中所有的元素都减了 1
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
# 将 X 矩阵中所有的元素都乘以 2
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
# 将 X 矩阵中所有的元素都除以 2
# 在 Python3 中一个 / 表示的是浮点数的除法， // 表示的是整数的除法
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [16]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [17]:
# 将 X 矩阵中所有的元素进行乘方
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [18]:
# 将 X 矩阵中所有的元素进行求余运算
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [19]:
# 将 X 矩阵中所有的元素进行取倒数
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [20]:
# 将 X 矩阵中所有的元素进行求绝对值
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
# 将 X 矩阵中所有的元素进行求正弦函数
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [22]:
# 将 X 矩阵中所有的元素进行求余弦函数
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [23]:
# 将 X 矩阵中所有的元素进行求正切函数
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [24]:
# 有sin()/cos()/tan()，就会相应的有arcsin()/arccos()/arctan()这些函数
# 将 X 矩阵中所有的元素进行取 e 的 X 次方
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [25]:
# 将 X 矩阵中所有的元素进行取 3 的 X 次方
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [26]:
# 与 np.power(3, X) 的效果是一样的
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [27]:
# 将 X 矩阵中所有的元素进行取 log 值，直接调用 np.log() 其实就是求的以 e 为底的自然对数
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [28]:
# 将 X 矩阵中所有的元素进行求以 2 为底的对数
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [29]:
# 将 X 矩阵中所有的元素进行求以 10 为底的对数
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [30]:
# numpy 的更加强大之处在于矩阵与矩阵之间的这种运算
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [31]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [32]:
# 矩阵 A 和矩阵 B 相加，矩阵之中对应的元素相加
A + B

array([[10, 11],
       [12, 13]])

In [33]:
# 矩阵 A 和矩阵 B 相减，矩阵之中对应的元素相减
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [34]:
# 矩阵 A 和矩阵 B 相乘，矩阵之中对应的元素相乘
A * B

array([[ 0, 10],
       [20, 30]])

In [35]:
# 矩阵 A 和矩阵 B 相除，矩阵之中对应的元素相除
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [36]:
# 线性代数中对应的严格的乘法实现
A.dot(B)

array([[10, 10],
       [50, 50]])

In [37]:
A

array([[0, 1],
       [2, 3]])

In [38]:
# 矩阵的转置
A.T

array([[0, 2],
       [1, 3]])

In [39]:
C = np.full((3, 3), 666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [40]:
# A + C

In [41]:
# A.dot(C)

### 向量和矩阵的运算

In [42]:
v = np.array([1, 2])
v

array([1, 2])

In [43]:
A

array([[0, 1],
       [2, 3]])

In [44]:
# 矩阵 A 和向量 v 相加，其实就是向量和矩阵中的每一行做加法
v + A

array([[1, 3],
       [3, 5]])

In [45]:
# 用来查看 A 的第 0 维的数量，即 A 有多少行
A.shape[0]

2

In [46]:
# 用来查看 A 的第 1 维的数量，即 A 有多少列
A.shape[1]

2

In [47]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [48]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [49]:
# np.tile()传入的第 1 个参数为需要堆叠的向量，传入的第 2 个参数为一个元祖，
# (2, 1)代表着在行向量上面堆叠 2 次，在列向量上面堆叠 1 次 
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [50]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [51]:
v

array([1, 2])

In [52]:
A

array([[0, 1],
       [2, 3]])

In [53]:
# 矩阵 A 和向量 v 相乘，其实就是向量和矩阵中的每一行做乘法
v * A

array([[0, 2],
       [2, 6]])

In [54]:
# 线性代数中对应的严格的乘法实现
v.dot(A)

array([4, 7])

In [55]:
# 对于 1 个向量和 1 个矩阵进行乘法，numpy会自动的进行判断这个向量应该取行向量还是列向量
A.dot(v)

array([2, 8])

### 矩阵的逆

In [56]:
A

array([[0, 1],
       [2, 3]])

In [57]:
# 计算矩阵 A 的逆，linalg 是线性代数的缩写，inv 其实就是 inverse 的意思
# 也就是逆
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [58]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [59]:
# 用原矩阵乘以原矩阵的逆矩阵等于单位矩阵
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [60]:
# 用原矩阵的逆矩阵乘以原矩阵也是等于单位矩阵
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [61]:
# 并不是所有的矩阵都有逆矩阵，首先至少它要满足是一个方阵
X = np.arange(16).reshape(2, 8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [62]:
# np.linalg.inv(X)

In [63]:
# 求一个伪逆的矩阵
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [64]:
pinvX.shape

(8, 2)

In [65]:
# 只有方阵才有可能有逆矩阵，对于非方阵可以求它的伪逆矩阵
# 不完全为 0 是由于计算机的浮点误差造成的
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

In [66]:
pinvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  4.78783679e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.84494650e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-5.84467136e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952