### Fancy Indexing

In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
# 用来索引一个区间，采用切片的方法
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
# 第 3 个参数表示步长
x[3:9:2]

array([3, 5, 7])

In [5]:
# 想要访问 x[3]/x[5]/x[8]，而并不是等步长的数
[x[3], x[5], x[8]]

[3, 5, 8]

In [6]:
ind = [3, 5, 8]

In [7]:
x[ind]

array([3, 5, 8])

In [8]:
# 索引数组不仅仅可以是一维数组，还可以是二维数组
ind = np.array([[0, 2],
                [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
X[0, col]

array([1, 2, 3])

In [12]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [13]:
# 使用 bool 数组这种用法是非常重要的
col = [True, False, True, True]

In [14]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array 的比较

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
# 将 x 中所有的元素都去和 3 做一个比较
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
(x < 3).dtype 

dtype('bool')

In [18]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [19]:
(x > 3).dtype

dtype('bool')

In [20]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
(x <= 3).dtype

dtype('bool')

In [22]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
(x >= 3).dtype

dtype('bool')

In [24]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [25]:
(x == 3).dtype

dtype('bool')

In [26]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [27]:
(x != 3).dtype

dtype('bool')

In [28]:
# 这里的 x 是一个一维数组，而不是一个具体的数
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [29]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [31]:
(X < 6).dtype

dtype('bool')

In [32]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
np.sum(x <= 3)

4

In [34]:
# np.count_nonzero()可以计算出传进来的数组中非 0 的元素的个数
np.count_nonzero(x <= 3)

4

In [35]:
# 数组中是否有任何的非 0 元素
np.any(x == 0)

True

In [36]:
# 数组中是否所有的元素都小于 0，只要有任何一个元素小于 0 的话，结果都会返回 True
np.any(x < 0)

False

In [37]:
# 和 any() 为相反的意思，表示必须所有的都满足
np.all(x >= 0)

True

In [38]:
np.all(x > 0)

False

In [39]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
# 求偶数的个数
np.sum(X % 2 == 0)

8

In [41]:
# 沿着列的方向，就是去看每一行有多少个偶数
np.sum(X % 2 == 0, axis = 1)

array([2, 2, 2, 2])

In [42]:
np.sum(X % 2 == 0, axis = 0)

array([4, 0, 4, 0])

In [43]:
np.all(X > 0, axis = 1)

array([False,  True,  True,  True])

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
np.sum((x > 3) & (x < 10))

6

In [48]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-48-d834f65999a2>, line 1)

In [49]:
np.sum((x % 2 == 0) | (x > 10))

11

In [52]:
# 非运算
np.sum(! (x == 0))

SyntaxError: invalid syntax (<ipython-input-52-0c96d91b63f7>, line 2)

In [53]:
# 非运算
np.sum(~ (x == 0))

15

In [55]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [56]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [62]:
X[X[:, -1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

#### 对于更加高级的表格处理，我们并不是直接操作 Numpy 数据，而是会使用 Pandas 库
#### Pandas库提供了一个DataFrame这样的数据结构，可以更加灵活的处理我们的数据