In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 0 就是良性肿瘤，1 就是恶性肿瘤
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.71637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1,1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [2]:
%run kNN_function/kNN.py

In [4]:
# k 在这里选择的是 6
predict_y = kNN_classify(6, X_train, y_train, x)

In [5]:
predict_y

1

### 使用 scikit - learn 中的 kNN

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
# 在 sklearn中的所有的机器学习算法都是以面向对象的形式进行包装的，所以首先需要做的是类的实例化
# 这里的 n_neighbors 就是 kNN 算法中的 k 的值
kNN_classifier = KNeighborsClassifier(n_neighbors = 6)

In [9]:
# 将 kNN_classifier 做一遍 fit 的过程，也就是拟合的过程
# sklearn对于机器学习的 fit 函数是有一个返回值的，这个返回值其实就是这个机器学习对象自身
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [10]:
# kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [13]:
X_predict = x.reshape(1, -1)

In [14]:
X_predict

array([[8.09360732, 3.36573151]])

In [12]:
kNN_classifier.predict(X_predict)

array([1])

In [16]:
y_predict = kNN_classifier.predict(X_predict)
y_predict

array([1])

In [17]:
y_predict[0]

1

### 重新整理我们的 kNN 的代码

In [18]:
%run kNN/kNN.py

In [19]:
# clf 是 classifier 的缩写，说明它是一个分类器
knn_clf = KNNClassifier(k = 6)

In [20]:
knn_clf.fit(X_train, y_train)

kNN(K = 6)

In [22]:
# 由于 fit() 函数返回的是自身 self
knn_clf.predict(X_predict)

array([1])

In [24]:
y_predict = knn_clf.predict(X_predict)
y_predict

array([1])

In [25]:
y_predict[0]

1

In [ ]:
# kNN 算法本身在预测过程中是非常耗时的